### ISSUE TITLE
Updated from HF Patch 1.2 to 1.8 (Stuck at Loading Screen when initiating H-Scene)

### ISSUE THREAD

**Issue by LucOfTrueWind** [ManlyMarco/KK-HF_Patch#1]
It's been actually a long time since i used the HF Patch, and i somehow downloaded v1.2 back in June..
For months, i lost internet connection.. So this time, i managed to get my hands on HF Patch v1.8 which i just found out this morning.. however there was a problem after i installed it.. Everything seems to work
except when everytime i initiate H with a girl, or whenever i try Free-H at the main menu, it's always stuck
halfway with the loading bar.. Am i the only one experiencing this?

**Comment by ManlyMarco** [comment]
This is a known issue in sideloader and a combination of other mods. Try the v1.9 version I just released, it should fix the issue. Install it on default settings and chose to remove all old mods just to be safe.

If you still get this issue, please follow the discord link at the end of installation and ask in the #help channel. This will be the fastest way to get it fixed.
