### ISSUE TITLE
source file corrupted

### ISSUE THREAD

**Issue by szyuGH** [ManlyMarco/KK-HF_Patch#10]
I tried to downloaded the HF Patch about 4 times now via torrent link...
But when I want to install the patch (I do all that is described in the description for steam), at one point I get the following error:
![image](https://user-images.githubusercontent.com/12794711/62580487-852e5980-b8a6-11e9-98c6-661bbadf3b8a.png)

Each time I downloaded on different files... I can't use the mirror download because of the download size limit... So is there a way to solve this problem?

**Comment by ManlyMarco** [comment]
Try doing this: Scan your hard drive for errors, restart, and in your torrent client make it verify the downloaded files.
