### ISSUE TITLE
[feature request] Backup mods. Do not delete.

### ISSUE THREAD

**Issue by Tom-Neverwinter** [ManlyMarco/KK-HF_Patch#11]
I'm tired of using this and it deletes all the mods.
This tool fails to check versions or backup.

I may use this tool to change one item and I can un-check everything and it still nukes everything.

**Comment by ManlyMarco** [comment]
Did you turn off the "remove all old mods / plugins" settings when installing? With these off hf patch shouldn't remove anything unless it can cause conflicts or if you're installing a newer version of it.

**Comment by Tom-Neverwinter** [comment]
yup. still deleted all mods.

**Comment by ManlyMarco** [comment]
Added automatic backup of BepInEx folder in 3.0
