### ISSUE TITLE
warning file in install can glitch windows

### ISSUE THREAD

**Issue by maxlefou** [ManlyMarco/KK-HF_Patch#12]
By warning file, i mean the file you've added in MEGA about instructions for users. The single file named `ALL.exe AND.bin FILES ARE NECESSARY. USE THE.torrent FILE TO DOWNLOAD IF YOU HIT THE MEGA LIMIT.`

This very file can glitch all windows by its simple presence, for instance when you download the whole patch folder using the mega program. This file then can be impossible to delete, probably because of the use of `.` everywhere, confusing windows. Because of that, when attempting to remove the file, windows gives an error and refuses totally to delete it. I could manage to get rid of it by using git bash and use the `rm` command, though.

So I suggest you rename this file so it doesn't use any `.`, maybe it will fix the problem? (because i don't know what else can cause an error like this. I already seen windows complaining aboug making files starting with a `.` like a `.gitignore` or stuff)

**Comment by ManlyMarco** [comment]
It was most likely caused by the dot at the end of filename. I renamed the file, thank you for the heads up!
