### ISSUE TITLE
ModBoneImplantor missing in installation

### ISSUE THREAD

**Issue by MayouKurayami** [ManlyMarco/KK-HF_Patch#16]
ModBoneImplantor is not listed as a component during installation.

Not sure if it's supposed to be installed by default, but after a custom installation it's not present in the BepInEx directory.

**Comment by ManlyMarco** [comment]
It's installed to BepInEx/plugins when you select sideloader modpack. https://github.com/ManlyMarco/KK-HF_Patch/blob/9297427caa3f416ee8065f69c7ba8c2de5ce44c7/patch.iss#L263
