### ISSUE TITLE
[suggestion] add a list of the mods added

### ISSUE THREAD

**Issue by maxlefou** [ManlyMarco/KK-HF_Patch#18]
I'm getting more and more complaints of missing mods in my cards and i'm kinda surprised since i rarely put non-hf-patch mods in my install (when I do, it's usually for the studio only on top of that) So i'm wondering what's going on. And I haven't found a way to quickly check if the missing mod they talk about is in the patch or not.

So what would be good is to put a list of the zipmods available in the patch. No need for something fancy, just a list, eventually with the files path and maybe their version number, in txt. I think something like this can be generated with a simple batch script.

**Comment by ManlyMarco** [comment]
I'm using the Sideloader Modpacks, you can see their changelogs and contents in the creator's posts here https://www.patreon.com/DeathWeasel/posts?filters%5Btag%5D=Sideloader%20Modpack
For contents of the packs click on the first link.

I think posting this information here would be redundant and not used by many people.

**Comment by maxlefou** [comment]
Thanks for the link... I'll check it out.
