### ISSUE TITLE
White List JS Torrent

### ISSUE THREAD

**Issue by JosephVincentLaMantiaIV** [ManlyMarco/KK-HF_Patch#19]
This was provided by the client; I hope this can be done!
JSTorrent reports itself to the tracker a "User-Agent" string the same as the underlying browser (e.g. "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"). (current limitations disallow changing this)
It adds an "X-User-Agent" string of the form: (JSTorrent/{version}) (current x-user-agent string version: "JSTorrent/2430"
Its peer id begins with "-JS{version}-", currently peer id begins with "-JS2430-"

**Comment by ManlyMarco** [comment]
The tracker I'm currently using is out of my control in this regard unfortunately. Is this really an issue? The torrent should still work fine with only DHT and peer exchange.
