### ISSUE TITLE
Confusing uncensor mods

### ISSUE THREAD

**Issue by maxlefou** [ManlyMarco/KK-HF_Patch#2]
I found how to change the uncensor mods in the settings menu and all... But there's a shit load of it, and everytime i try one, I must reload the H scene to see the changes... Not a huge deal, though.

But, the names of the mods are very confusing. Like, the only one i found with a regular cock so far was SOS.trap, all the others giving pussies to males. It took me around a half hour to kinda get back the settings i had in the previous update of your patch. :/

So, if you can occasionally add with the names some clues like "peen", "puss" and "futa", whatever, to stop confusion..  Is that possible?

Thanks and keep up the good work. :)

**Comment by DeathWeasel1337** [comment]
That's more an issue with UncensorSelector itself than the HF Patch
https://github.com/DeathWeasel1337/KK_Plugins#readme

Currently I don't think there's a good way to label the uncensors from the plugin settings, however they are all appropriately labeled in the character maker itself. Try them out inside the character maker to see which one you like best before assigning a default. You can even choose different uncensors for different characters.

**Comment by Matihood1** [comment]
I have another problem with this new selector: It doesn't have the KK LO pussy v0.5 male uncensor, which was available in the HF patch earlier, only the female one. And it's a pretty big problem for me because I've already grown used to it. And apparently it's not that easy to make an uncensor compatible with the selector if you don't know virtually anything about modding in Unity.

Could you by any chance re-add the option to select the uncensors from the installer as an alternative to the UncensorSelector?

**Comment by petran79** [comment]
Another issue is that the Atapi2.1 50% mod does not work while in-game. Eg in the Character Editor, characters appear with increased bust size, but while in-game they change to normal size.

**Comment by maxlefou** [comment]
I made a visual guide so people can now how the mods look without having to reload everytime. There's one for girls and one for boys.
[bitsguide.zip](https://github.com/ManlyMarco/KK-HF_Patch/files/2974079/bitsguide.zip)

**Comment by ManlyMarco** [comment]
@Matihood1 Latest versions of uncensor selector now have the KKLO male uncensor.
@maxlefou Thanks! Hopefully the new version of selector will be more convenient to use.

Any uncensor selector bugs/requests should go to it's repository [here](https://github.com/DeathWeasel1337/KK_Plugins/issues) so @DeathWeasel1337 can see them.

New version of HF Patch will include latest selector and maybe pictures that @maxlefou posted and will hopefully be easier to use. For now I'm closing the issue, thank you for the reports!
