### ISSUE TITLE
Constantly getting corrupted files from the torrent.

### ISSUE THREAD

**Issue by Kitsune97** [ManlyMarco/KK-HF_Patch#20]
Been trying to install the HF patch for the past couple of days now, and I have ran into the same problem repeatedly where I will get to the installation part but suddenly one of the files is corrupted, I have tried scanning my hardrive, using two different torrents (Qbittorrent and Utorrent), verifying my game on steam and redownloading the patch, and force rechecking the torrent and yet I still can't sort, any advice?

**Comment by ManlyMarco** [comment]
Both of these clients should work fine. You can check the downloaded files in the torrent client by right clicking in the list and selecting force recheck. Make sure your antivirus isn't interfering, and try to restart your PC before trying to install the patch again. Also make sure you have the latest release of the patch and that you are not running it from anywhere inside the game directory (keep it in your downloads).
