### ISSUE TITLE
Game crashes on exit and no "Illusion" intro voice

### ISSUE THREAD

**Issue by Matihood1** [ManlyMarco/KK-HF_Patch#24]
So I've been having these issues since HF Patch 3.4 iirc. When I try to exit the game (both Koikatsu and Studio), it crashes instead. Also, when launching Koikatsu, I don't get the "Illusion" voice line on startup. I only get the "Koikatsu" line for whatever reason (I'm pretty sure I didn't check the Custom Intro Voices mod when installing the patch). The crash files:
[2020-12-21_132504.zip](https://github.com/ManlyMarco/KK-HF_Patch/files/5724289/2020-12-21_132504.zip)

**Comment by ManlyMarco** [comment]
Update DragAndDrop to fix crash on exit and turn off fast startup in TitleShortcuts settings.

**Comment by Matihood1** [comment]
The crashing issue got fixed but I'm not actually sure how to turn off fast startup in TitleShortcuts. There's only the "Automatic start mode" in the plugin's .cfg file but that's already disabled for me.

**Comment by ManlyMarco** [comment]
Remove that plugin entirely then.

**Comment by Matihood1** [comment]
Fair enough. I guess I'll contact the author of the plugin and tell them about this. Maybe they'll add an option to just disable the fast startup. Closing the issue.
