### ISSUE TITLE
deleting folders again

### ISSUE THREAD

**Issue by Tom-Neverwinter** [ManlyMarco/KK-HF_Patch#25]
For the longest time I put addons in and they would stay.

then the updated version of the patcher wiped them out

https://github.com/ManlyMarco/KK-HF_Patch/issues/11

so I moved everything to a "TEMP" folder inside Koikatsu folder

which has worked great up to at least 3.3?

now it deletes the "TEMP" folder in 3.7

This behavior is really annoying and forces me to use multiple folders for this game.  [It also didn't care that I ran the updater from inside this folder to update.] I will no longer be using this software as its just creates more issues, and forces the creation of more clutter. 

Please set a designated folder for storage/backup or stop deleting everything for no reason.

**Comment by ManlyMarco** [comment]
The temp folder is used by kkmanager and is automatically cleaned up by both kkmanager and hf patch, so do not put anything important in there.

If you don't want the patch to remove your old plugins then during installation uncheck deleting old plugins. The patch might still remove some plugins that are known to be incompatible or cause issues.

As always, you can restore old plugins from the backup file generated by hf patch in your game directory. You don't have to make a backup manually.
