### ISSUE TITLE
HF Patch 3.8 is missing some translation files

### ISSUE THREAD

**Issue by niraimegumi** [ManlyMarco/KK-HF_Patch#28]
After installing HF Patch 3.8, in story mode, the official translations for vanilla personalities are overwritten by machine translations of lower quality. How to fix? I used the "recommended" preset in the installer, and had HF Patch 3.7 before updating.

The magnet link for 3.7 no longer seems to work by the way, it gets stuck in "downloading metadata."

**Comment by ManlyMarco** [comment]
Are you sure you didn't uncheck the translations by accident, or changed the patch language at start to something other than English? You can try reinstalling the patch with default settings, or restoring the previous translations from the backup the patch created in your game directory.

**Comment by niraimegumi** [comment]
Yes, I'm sure. Patch language was set to English. Everything was left at "recommended", and I even tried installing HF Patch over BetterRepack RX9 and, sure enough, translations were gone as well. Re-installing XUnity.Autotranslator didn't help. Again, if I had known about this issue I wouldn't have deleted the plugin backup, so I'm sticking with RX9 until the next release of HF Patch.

**Comment by Ivan-Q95** [comment]
Same here. I used HF Patch to update my KK from 3.5 to 3.9 and now I have over a half of my cards with machine-translated names. For example, if earlier it was "Scathach", now it's "Sukasaha" and so on. I tried several times to reinstall HF Patch with different settings, including the recommended ones, but nothing changed at all

**Comment by ManlyMarco** [comment]
So it's card names in particular that are the issue and not actual game text?

**Comment by Ivan-Q95** [comment]
> So it's card names in particular that are the issue and not actual game text?

All other in-game text seems to be correct.  At least I haven't seen any inaccuracies other than card names.

**Comment by ManlyMarco** [comment]
Should be fixed in v3.11, please reopen the issue if the translations are still having issues.
