### ISSUE TITLE
Stuck in “Now Loading...” in vr 

### ISSUE THREAD

**Issue by yuhyuhyuhD** [ManlyMarco/KK-HF_Patch#29]
Hello so the hf patch seems to work fine in normal Koikatsu. But when I use the VR side of it it will allow me to pick both meme era of the scene but then when I continue, it will only show a white screen in the head set, if you move you’re head out of the white bubble you can see the scene is set up and the girl is standing there and everything it just won’t load. On the pc monitor not the headset it will just have the little “Now loading...” in the bottom left hand corner continuously. Any Ideas what I messed up?

**Comment by ManlyMarco** [comment]
Which version of the patch, and which release of the game? Did you get the latest update on Steam?

**Comment by yuhyuhyuhD** [comment]
Patch 3.8 and for the steam version do you want the Build ID? I’m not really sure how to find the game version other than that. But I do know the game is the most up to date.

**Comment by ManlyMarco** [comment]
The issue is because of the latest update on steam. The solution is to revert to previous version of the vr module. Check pins in #help channel on discord for a revert tool. Next version of the patch will fix this.

**Comment by yuhyuhyuhD** [comment]
Oh ok thanks! And also follow up question when a new version of the hf patch comes out do I have to download the whole new patch or can I just use the updater in the patch launch window to update the stuff I need to?

**Comment by ManlyMarco** [comment]
Updater only updates content mods like clothes. You need the full patch to get game and plugin updates.

**Comment by yuhyuhyuhD** [comment]
Ok thank you very much! And I appreciate the hard work you’re doing :)
