### ISSUE TITLE
Installing the HF Patch over a REPACK..

### ISSUE THREAD

**Issue by LucOfTrueWind** [ManlyMarco/KK-HF_Patch#30]
It isn't really much of an issue, but more of just a consultation..
I actually installed this into my my own old copy of Koikatsu, which has the "AFTERSCHOOL" DLC.. But only the AFTERSCHOOL DLC. So far, everything is going well, no issues to report.

However, I found  a REPACK from a user in nyaa uploaded by a user named "ScrewThisNoise" which includes ALL DLCs currently available for the Japanese Version.. I really just prefer the HF Patch over any repacks, but still..
A Complete collection is.. something..?

My Question is.. Do I just install the latest version of HF Patch on this or are there other extra steps needed to be done?
And also what is this "vanilifier script"? ScrewThisNoise said in one of his older uploads about A YEAR AGO that this must be done before installing the HF Patch..

If I could just transfer the DLCs themselves from folder to another, I'd do it, but.. What do you think, kind sir?

**Comment by LucOfTrueWind** [comment]
Oh and also, I forgot to mention.. The Torrent included two rar files. The 20GB File which I assume is the game AND the DLCs, and the other has the "OPTIONAL" Tag which are optional sideloaders..
Since I tried downloading it via torrent, I was given a choice of whether I should download the OPTIONAL included Sideloaders, but I chose not to..

**Comment by ManlyMarco** [comment]
You can install the HF Patch directly over it with no issues. Make sure it's the latest version of the patch and optionally run the script before patching to remove unnecessary files. No need to install the optional modpack, the patch has it.

**Comment by LucOfTrueWind** [comment]
Ah,  I see.. I'll try that. And Thank you very much!
