### ISSUE TITLE
Magnet Link Not Working.

### ISSUE THREAD

**Issue by Kitsune-Nova** [ManlyMarco/KK-HF_Patch#32]
I'm still pretty new to using torrent and magnets, but the link is just plain text for me, so when I try and click on it, nothing happens. And when I copy/paste it into UTorrent it does nothing.
I don't know if I'm being an idiot or if my computer is just refusing to allow it, but any help will be appreciated.

**Comment by ManlyMarco** [comment]
Try using the latest version of qBittorrent and make sure you copy the entire magnet link.

**Comment by Kitsune-Nova** [comment]
Ah, that worked, thank you!
