### ISSUE TITLE
Mods are gone

### ISSUE THREAD

**Issue by JaysuMochi** [ManlyMarco/KK-HF_Patch#35]
After updating to HF patch version 3.14, all of my .zipmods are completely gone from my mods folder. This is messed up but I’m trying to recover them using a recovery tool. Hoping it works.

**Comment by ManlyMarco** [comment]
Did you use the full patch or the light patch? Maybe the modpacks got unchecked in the component list and removing all old mods got checked. Unless you mean your custom zipmods got removed, to keep those you need to uncheck removing old zipmods.

**Comment by JaysuMochi** [comment]
Yeah it the custom zipmods that got removed. Thank you for letting me me know. Next time I’ll make sure to uncheck them.
