### ISSUE TITLE
the video export in v3.15 won't open when i press ctrl + E

### ISSUE THREAD

**Issue by StopTheRussian** [ManlyMarco/KK-HF_Patch#37]
![Screenshot (13)](https://user-images.githubusercontent.com/100501041/155876926-77541b2a-a77e-4dac-9084-764c971e3abe.png)

**Comment by ManlyMarco** [comment]
[debug build.zip](https://github.com/ManlyMarco/KK-HF_Patch/files/8148818/debug.build.zip)
Try replacing the dll with this one and see if it fixes the issue.

**Comment by ManlyMarco** [comment]
Did the debug build fix the issue or not?

**Comment by StopTheRussian** [comment]
Yes, it is working.

Vào 23:11, T.3, 1 Th3, 2022 ManlyMarco ***@***.***> đã viết:

**Comment by StopTheRussian** [comment]
Thanks.

Vào 23:21, T.3, 1 Th3, 2022 ManlyMarco ***@***.***> đã viết:
