### ISSUE TITLE
Changing clothes error when plugin data has been modified by other plugin is not guarantee integrity 

### ISSUE THREAD

**Issue by StopTheRussian** [ManlyMarco/KK-HF_Patch#39]

**Comment by ManlyMarco** [comment]
Does this happen with all characters?

**Comment by StopTheRussian** [comment]
Yeah, all of them

**Comment by StopTheRussian** [comment]
Yeah, but can you fix this ?

Vào 17:39, Th 3, 1 thg 3, 2022 ManlyMarco ***@***.***> đã
viết:

**Comment by ManlyMarco** [comment]
I can't reproduce the issue, please ask in the #help channel on the discord server.

**Comment by StopTheRussian** [comment]
I searching in discord channel everywhere and there is no #help

Vào 23:11, T.3, 1 Th3, 2022 ManlyMarco ***@***.***> đã viết:

**Comment by ManlyMarco** [comment]
This shouldn't be happening any more sice AccStateSync isn't used.
