### ISSUE TITLE
in Studio all certain scenes make all the characters busts flat

### ISSUE THREAD

**Issue by FAKINFAAK** [ManlyMarco/KK-HF_Patch#4]
when ever i open studio now after the 2.4 hf patch all the characters bust sizes all go to 0 every one of them on every scene i load. help plz

**Comment by ManlyMarco** [comment]
Can you check your koikatu_data\output_log.txt file for crashes? Or just send it to me here or in the discord server's #help channel.

**Comment by FAKINFAAK** [comment]
[output_log.txt](https://github.com/ManlyMarco/KK-HF_Patch/files/2974928/output_log.txt)

like this?

**Comment by ManlyMarco** [comment]
Try removing BepInEx\IPA\KK_Kiyase.dll

**Comment by FAKINFAAK** [comment]
Didn't seem to work even if i removed it. 
:(

**Comment by ManlyMarco** [comment]
Hop on the discord server and ask in #help channel https://discord.gg/zS5vJYS
