### ISSUE TITLE
Some Clothing Tops Don't Render

### ISSUE THREAD

**Issue by Kirbyarm** [ManlyMarco/KK-HF_Patch#40]
I'm not exactly sure where to post an issue like this, but this felt like a good spot. If anyone has an idea it's probably you, Marco.

Anyways, when walking around the school, and this happens 100% of the time, certain character's shirts ("Top") just simply aren't there when they should be. But when I interact with them (aka entering a conversation), it's there until I leave the convo and the school is loaded again. They also render fine in H scenes. I don't think this has anything to do with persist clothes after some tests, also since it only appear to be certain shirts on certain cards. I've tried to gather as much info and samples as I could about this, mostly images.

---

The witch hat girl's Top is: [ZX] Megumin Top
[School](https://i.imgur.com/JhZ5eDH.png)
[Conversation](https://i.imgur.com/Z50gSVv.png)
[Actual Card](https://steamuserimages-a.akamaihd.net/ugc/1850421908551280986/DEC540D2E529E65B549B9C8DD35FF14681E57433/)

The blonde (Android 18)'s Top is: Dress Shirt(sth2) *Though in this case the shirt renders but her shoulders are invisible, I suspect it could be related*
[School](https://i.imgur.com/rWpYv55.png)
[Conversation](https://i.imgur.com/hsL8IIO.png)
[Actual Card](https://steamuserimages-a.akamaihd.net/ugc/1850421908551280825/ED84BCD6B07C0BDED408BC0A1BBABCB164195D8C/)

The green eyed girl with denim looking clothes (Monika)'s Top: Solitude Top
[School](https://i.imgur.com/DA3Bwfq.png)
[Conversation](https://i.imgur.com/gWkRmFV.png)
[Actual Card](https://steamuserimages-a.akamaihd.net/ugc/1850421908551280665/09E8773D4E5BB6C9DC67795C4E972DBFCCBE6213/)

And here's an image of just these three as students in their own save file in the classroom idling about:
[Classroom](https://i.imgur.com/2PrrkSQ.jpeg)

Output Log file after loading into the school of the save involving them:
[output_log.txt](https://github.com/ManlyMarco/KK-HF_Patch/files/8195490/output_log.txt)

---

Do you know what's causing this or have any ideas how to fix it for their cards? This would really help for other cards like these that I encounter in the future with similar issues!

**Comment by ManlyMarco** [comment]
1. Make sure force high poly is turned on in plugin settings.
2. Try turning off async clothes loading in plugin settings.

**Comment by Kirbyarm** [comment]
Hmm. Even after rebooting with the async option disabled, the issue persists.

I also don't think I have [the mod that has said force high poly feature.](https://i.imgur.com/o36HAtE.png)

Think it would help to try it? If so, may I please know what it's called? Otherwise do you have any other ideas?

**Comment by ManlyMarco** [comment]
It's installed by default by the patch https://github.com/ManlyMarco/KK-HF_Patch/blob/master/components.iss#L105

**Comment by Kirbyarm** [comment]
Took quite a while to download and install, but thanks. I actually installed it over a clone of my current install and just moved over a couple of plugins from the HF patched install, including the high poly one.. which failed to load until I also moved over the dll and xml for the HF patched KKAPI, which makes sense.

It appears high poly does indeed fix the issue! Thanks a lot for identifying it!

---

Tested my 3-student save to see. Now I'm terrified about the 8 GB RAM for 10 characters warning as I'm about to attempt loading my 98 student file >_<; Yeah..... that was kinda scary. My 32 GB of RAM hit 99% when first loading in, dropping to about 80-85% after that. FPS is significantly lower and as much as I enjoy the jiggling booties and boobies as any human of culture would, while they walk it's doing so in such an erratic fashion that it looks unnatural and glitchy. I'd love to just straight up try the HF Patch install for my main save, but I have a feeling I don't have enough RAM for that... so I might just have to avoid high poly clothing unless something gets developed specifically for that.

However... *big pog* to you for KK_Fix_MainParam! Not being able to kiss the math teacher under any circumstance was beginning to drive me mental. Bonus being able to edit students' voices and all that too! I really wonder why the game allows fully importing characters over the students, story heroines and teachers but not character information. 🤔

Will keep high poly installed for smaller saves for sure though, it looks quite nice I must say. If only 64 GB RAM kits weren't so ridiculously expensive.

I will be taking a much closer look through the rest of the plugin differences between the installs I have and pull over ones that I think would be a good fit in my pack. Already have 50~ GB of modded content, so I don't think I'll need much from there. Sorry, went on a bit of a write there.

---

That being said, besides the plugins and being up to date, are there any other great reasons for completely switching over to the HF patched version instead, that you can think of off the top of your head?

**Comment by ManlyMarco** [comment]
HF Patch is meant to be a known good starting point to use as it is or to continue modding further if you want to add something less common. If you know what you're doing and want to spend time hunting individual updates then it's not that important.
