### ISSUE TITLE
Installing patch breaks some After Party DLC translations

### ISSUE THREAD

**Issue by ADifferentOther** [ManlyMarco/KK-HF_Patch#41]
I've been using the patch without issue for a while now, but recently I decided I'd buy the After Party DLC on steam. On an install without the patch, all the translations work as expected (e.g. the English version of the logo is displayed on the title screen and the new option in the Have Sex menu reads "Threesome"), however as soon as I install the patch all of these translations are removed. All text that is a part of the base game still appears in English, but anything new to the AP DLC appears in Japanese. I've tried patching both my old install and a clean install of the game, as well as disabling and enabling almost every option in the installer menu to no avail. Any ideas?

**Comment by ADifferentOther** [comment]
![image](https://user-images.githubusercontent.com/101262039/157444957-65a4fe38-d77e-49af-83b8-b9885b9b62c2.png)
Example

**Comment by ADifferentOther** [comment]
Installing the special patch from Illusion fixed the translations, however seems to have broken a lot of the plugins. In the character creator any menu created by a plugin is just blank, and nothing added by plugins is being loaded from cards.
![image](https://user-images.githubusercontent.com/101262039/157448372-36bacd0e-9840-4771-85c6-1bb660e855cc.png)
For reference I'm using v3.15, and I installed the HF patch after the DLC, then the Illusion special patch after that just now.

**Comment by ManlyMarco** [comment]
What are the contents of BepInEx\Translation\en\Texture after installing the patch over the DLC? (tell it to remove all old plugins and settings)

**Comment by ManlyMarco** [comment]
Weird, are the tutorials translated (specifically the 3P tutorial)?

**Comment by ADifferentOther** [comment]
![image](https://user-images.githubusercontent.com/101262039/157515256-d9f18ace-12a4-44c5-b255-25315f770844.png)
I'm guessing this is what you mean? In which case yeah all of the After Party tutorials are translated.

**Comment by ManlyMarco** [comment]
Can you try this one? Replace the existing zip with it. [Not in KKPAP.zip](https://github.com/ManlyMarco/KK-HF_Patch/files/8217560/Not.in.KKPAP.zip)

**Comment by ADifferentOther** [comment]
Yep, that's translated the threesome menu fine. They're different to the translations I get with the unpatched DLC (i.e. the tab says Group instead of Threesome), but that's not really an issue. Thanks for all of this!

**Comment by ManlyMarco** [comment]
It's not optimal, yeah, but it's the easiest and most reliable way to fix it. Thank you for the help, the fix will be included in the next version of the patch.

**Comment by ADRSIMTEK** [comment]
Do you have the link to download the threesome? Please.

**Comment by ManlyMarco** [comment]
> Do you have the link to download the threesome? Please.

Get the AfterParty / AfterSchool DLC.

**Comment by ADRSIMTEK** [comment]
> 

Is it on the Illusion website?

**Comment by ADRSIMTEK** [comment]
Thanks ! :)
