### ISSUE TITLE
Unable to use clothing data normally in the character editor and Studio.

### ISSUE THREAD

**Issue by Ivan-Q95** [ManlyMarco/KK-HF_Patch#42]
I keep seeing this for a few patches now:
When I want to load some accessories individually (show selection), the game slows down in the process, and then gives an error. Consequently, I can't put the clothes I want on a character without transferring an inappropriate hair or other accessory to them (or I have to choose not to load accessories at all)

This is very annoying because it prevents you from editing the character comfortably. Why does this happen at all, and is there any way to fix it? (Like bringing back an old version of some plugin without rolling back to the old patch?)

**Comment by ManlyMarco** [comment]
Fixed in latest patch.
