### ISSUE TITLE
Error opening data terminal

### ISSUE THREAD

**Issue by jdoexbox360** [ManlyMarco/KK-HF_Patch#43]
Here is the BepInex Log
`[Error  : Unity Log] UnauthorizedAccessException: Access to the path "G:\darksiders\AiShoujo\UserData\chara\female\ais_f_default.png" is denied.
Stack trace:
(wrapper dynamic-method) System.IO.FileStream.DMD<System.IO.FileStream::.ctor>(System.IO.FileStream,string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,System.IO.FileOptions)
(wrapper dynamic-method) System.IO.FileStream.DMD<System.IO.FileStream::.ctor>(System.IO.FileStream,string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,bool)
(wrapper dynamic-method) System.IO.FileStream.DMD<System.IO.FileStream::.ctor>(System.IO.FileStream,string,System.IO.FileMode,System.IO.FileAccess)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess)
AIChara.ChaFileControl.SaveCharaFile (System.String filename, System.Byte sex, System.Boolean newFile) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.Scene.MapScene.SaveProfile (System.Boolean isAuto) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.PlayerActor.StashData () (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.DevicePoint.<Start>m__0 () (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.CommandLabel.OnInputAction (System.Boolean isDown) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.CommandLabel.<Start>m__3 (System.Boolean x) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <0a7d89e4511e4bdeb215f76ca00fd04e>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <0a7d89e4511e4bdeb215f76ca00fd04e>:0)
AIProject.UI.DownCommandDataBase.OnInvoke (Manager.Input input) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.UI.CommandDataBase.Invoke (Manager.Input input) (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
AIProject.CommandLabel.OnUpdateInput () (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
Manager.Input.SendPressedActionEventToSelectedObject () (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)
Manager.Input.Update () (at <df18494cc0c54d2f8fbaac18549a7c3b>:0)`

**Comment by ManlyMarco** [comment]
Looks like a file permission issue, try rebooting your computer and if the error persists try moving your game to a different directory.

**Comment by jdoexbox360** [comment]
Sorry I searched hf patch instaid of hf patch ai should but I even ran game as admin and it failed

**Comment by jdoexbox360** [comment]
I will post for ai-hf patch [here](https://github.com/ManlyMarco/AI-HF_Patch/issues/16).
