### ISSUE TITLE
accessory states GUI BUG

### ISSUE THREAD

**Issue by meagtw0445** [ManlyMarco/KK-HF_Patch#44]
accessory states GUI Always have problems accessing files
I keep repeating the accessory states program
always always always go back to the original state
With luck, there will be no problem
The previous version did not have this problem
it drives me crazy😭😭😭😭😭😭😭😭😭😭

**Comment by ManlyMarco** [comment]
Please report accessory states issues here https://github.com/jalil49/Maker_Tools/issues
