### ISSUE TITLE
Hash of file doesn't match

### ISSUE THREAD

**Issue by MGY6969** [ManlyMarco/KK-HF_Patch#46]
![imagen_2022-07-05_203916493](https://user-images.githubusercontent.com/101908078/177393809-1dd073af-b400-418f-bc45-d38cef35d032.png)
I already tried redownloading

**Comment by ManlyMarco** [comment]
It's definitely not a bug in the patch if that's what you're asking. You can try redownloading the exe in case it got corrupted in a way that corrupted the hashes, but most likely it's just a corrupted part.
