### ISSUE TITLE
ACC undo no work

### ISSUE THREAD

**Issue by an94444** [ManlyMarco/KK-HF_Patch#48]
ACCundo 0.9.0 can't work in HF3.16 until I disable MoreAccessories 2.0.21. 
Because old  MoreAccessories versions do not support.

**Comment by jdoexbox360** [comment]
Try doing it again (it probably won't work) but you should copy the black console window (yes, the whole thing) while doing this. Just select everything like normal and left click one everything is selected. Paste it here so ManlyMarco or anyone else can get a better understanding of this problem/bug and fix it.
