### ISSUE TITLE
Why did you replaced acc state sync?

### ISSUE THREAD

**Issue by ctmbottomtext** [ManlyMarco/KK-HF_Patch#49]
Accessory state mod is atrociously bad, it's GUI is horrendous and unintuitive compared to acc state one.......

**Comment by ManlyMarco** [comment]
AccStateSync got replaced because of compatibility issues and an uncooperative author. You can post issues for the new plugin here https://github.com/jalil49/Maker_Tools/issues, it's currently getting a partial rewrite.
