### ISSUE TITLE
Patch always installs base characters

### ISSUE THREAD

**Issue by Yamiji** [ManlyMarco/KK-HF_Patch#5]
I updated from 2.4 to 2.5, made sure to not check the "install default characters" checkbox, but the patcher installed them all anyway, overwriting the changes I did to some of them.

**Comment by Matihood1** [comment]
Are you sure you also unchecked the "translated cards, scenes and backgrounds"? Because that also installs the base character cards.

**Comment by Yamiji** [comment]
It was sufficiently long ago that I can't be sure. I will update after next patch update.

**Comment by ManlyMarco** [comment]
I think it's fixed now
