### ISSUE TITLE
DarkTheme makes the game unplayable

### ISSUE THREAD

**Issue by mailforporn** [ManlyMarco/KK-HF_Patch#50]
I know it's optional, but it sounded nice in theory so I enabled it. Now none of the student cards are readable unless I completely mess up my monitor's brightness/gamma settings (very dark grey font on black background).
Worst yet, it's not really a mod in the sense of all other mods you include, managed by KKManager, so it can not even be disabled once installed.
It should really not be included with a patch so many people trust as the golden standard, or at least have a warning text that says it makes the game look bad and ugly and unplayable.

**Comment by ManlyMarco** [comment]
Will add a warning.
