### ISSUE TITLE
A lot of hair style items doubles and triples

### ISSUE THREAD

**Issue by SlimegirlNMS** [ManlyMarco/KK-HF_Patch#52]
There are a lot of doubled hair items, there are some item that are tripled.

**Comment by ManlyMarco** [comment]
Are you sure it's not just different variations? Check the item names. If there really are duplicate mods being loaded (you can check by right clicking the item in maker and clicking show info in the context menu), report them here https://github.com/BetterRepack/SideloaderModpackTracker/issues
