### ISSUE TITLE
Female character creator causes game to crash when selected

### ISSUE THREAD

**Issue by fujamora** [ManlyMarco/KK-HF_Patch#54]
Whenever female character is selected, game force crashes at abound 90% load, male creator functions normally, as well as the base game creator.

Error Log:
[error.log](https://github.com/ManlyMarco/KK-HF_Patch/files/10061088/error.log)

**Comment by ManlyMarco** [comment]
Move the game to a shorter directory path like D:\KK, if that doesn't help try rebooting and then reinstalling the game and patch.

**Comment by fujamora** [comment]
Thank you, it appeared that the culprit was One-drive as I moved the folder to a different directory and it worked fine.
