### ISSUE TITLE
Seems like some bugs in RealPOV v1.3 or conflicting with other mods

### ISSUE THREAD

**Issue by magicdolls** [ManlyMarco/KK-HF_Patch#55]
In school life mode，when begin a first sex, the RealPOV works no problem.
But when go in second and next sex ,I press back space key, but there is nothing happened.
I check f1 config of the RealPOV mod, but it seems no problem.

**Comment by ManlyMarco** [comment]
Should be fixed in v1.3.1 https://github.com/IllusionMods/KeelPlugins/releases/tag/build-271
