### ISSUE TITLE
[KK] Breast collision setting (in chest 2 section of body setting) doesn't work for costumes in the extra outfit slots (MoreOutfitSlots).

### ISSUE THREAD

**Issue by John1234152** [ManlyMarco/KK-HF_Patch#56]
[KK] Breast collision setting (in chest 2 section of body setting) doesn't work for costumes in the extra outfit slots (MoreOutfitSlots), especially in scene of character studio.

I really appreciate your wonderful mods. Thanks!

**Comment by ManlyMarco** [comment]
https://github.com/IllusionMods/KK_Plugins/issues/166
