### ISSUE TITLE
HF Patch 3.19 installation stuck on extracting Sideloader Zipmod Cache

### ISSUE THREAD

**Issue by DinhHoangDuy** [ManlyMarco/KK-HF_Patch#57]
I tried to install HF 3.19 but I was always stuck here for a long time. Do you know how I can fix it?

![image](https://user-images.githubusercontent.com/81969152/215302308-c4d37078-ad75-4a8d-ac03-db06277c5a8b.png)

**Comment by ManlyMarco** [comment]
Wait for 10 minutes and if it doesn't progress restart your PC and run the patch again.

**Comment by DinhHoangDuy** [comment]
> Wait for at least 10 minutes and if it doesn't progress restart your PC and run the patch again.

I did that before but it doesn't work either. Now I'm reinstalling HF patch 3.18

**Comment by ManlyMarco** [comment]
No one else reported this issue and I can't reproduce it, so I'm guessing it was a one-off. If it happens again, try rebooting your PC and moving the game to a directory like D:\Games\KK.
