### ISSUE TITLE
Only developer console shows up

### ISSUE THREAD

**Issue by Claks1** [ManlyMarco/KK-HF_Patch#6]
When I open the cheat engine it doesn't show anything but the dev console, none of the other windows.

**Comment by ManlyMarco** [comment]
Did you select cheat tools when installing the patch? It's optional.

**Comment by Claks1** [comment]
Yes, it is installed, but it still only opens that window...

**Comment by Claks1** [comment]
Ok I solved it thanks anyway

**Comment by ManlyMarco** [comment]
Mind sharing how you solved it and what was the actual issue?

**Comment by Claks1** [comment]
I just didn't copy correctly the files in the Bepinex folder.
