### ISSUE TITLE
Probably an issue with screen size

### ISSUE THREAD

**Issue by Kettle5000** [ManlyMarco/KK-HF_Patch#61]
I have tried all of the screen size provided by the launcher but non of them have work on fixing this, is there a way to make it fit or it must be like this? because is kind of annonying trying to add new frames in timeline and i just can't select some bones under colliders because of this
![image](https://user-images.githubusercontent.com/93736713/230945566-cbd768a2-80d7-4696-86f6-a0e7637d0bfb.png)

**Comment by ManlyMarco** [comment]
What's the issue exactly? You can zoom and resize timeline window as needed.
