### ISSUE TITLE
Card translation problem 

### ISSUE THREAD

**Issue by Ivan-Q95** [ManlyMarco/KK-HF_Patch#62]
Bruh, the translation of the cards is getting worse and worse. About two years ago, the card names were perfectly correct, but then they started using horrible machine translation. I recently switched from patch 3.18 to 3.20, and it looks like the cards that used machine translation are now in Japanese altogether, which is more than half of my characters for example. The names become normal only if I manually change them in the character editor. Btw, I always use the recommended installation, but if i choose "Translated cards, scenes and background" option to be enabled, nothing changes for me, really. This is terrible.

**Comment by ManlyMarco** [comment]
What cards are you talking about specifically? Which game? Main game or studio?

**Comment by ManlyMarco** [comment]
Closing stale issue, can't reproduce.
