### ISSUE TITLE
Not a serious issue, but...

### ISSUE THREAD

**Issue by lennuh1** [ManlyMarco/KK-HF_Patch#66]
In your "readme.md", at download section, the brackets "Install Personality Pack*" and "Install Afterschool*" do not redirect into correct page and shows a 403 error.

![image](https://github.com/ManlyMarco/KK-HF_Patch/assets/62141181/bc0bd848-e800-46b5-92e2-5c1217a913e2)

**Comment by ManlyMarco** [comment]
The links work fine for me, make sure the website isn't blocked.
