### ISSUE TITLE
Can't disable some mods

### ISSUE THREAD

**Issue by chikachika1** [ManlyMarco/KK-HF_Patch#68]
After the last update, I can't disable pregnancy, pov, ahegao and pushup using kk manager.  After restarting the game, these mods appear again.

**Comment by chikachika1** [comment]
I disabled pregnancy plus and some other mods without any issues

**Comment by ManlyMarco** [comment]
Can you post this issue in https://github.com/IllusionMods/KKManager/issues instead? Check if the physical dll files are renamed, if there are any errors in the log, and include what version of KKManager do you have now and what version did you have before if you can.
