### ISSUE TITLE
sperm juice drop time pull out it disappear 

### ISSUE THREAD

**Issue by zeetong333** [ManlyMarco/KK-HF_Patch#7]
Hi. I have problems a sperm juice drop time pull out it disappear in HF2.6 / it only me or not?
I remember it still work in hf2.5

**Comment by ManlyMarco** [comment]
Hello!

Can you give me exact steps on how to reproduce this issue?

**Comment by zeetong333** [comment]
hi I'm misunderstand it option in game "fluid type" is not open. now I can fix the problem.
Thank you! ^___^
