### ISSUE TITLE
Initial Settings/Launcher window changed

### ISSUE THREAD

**Issue by BAP00tato** [ManlyMarco/KK-HF_Patch#70]
I'm not sure if it's supposed to look like this
![image](https://github.com/ManlyMarco/KK-HF_Patch/assets/112852330/8286fbba-ff0a-4b5b-930b-e41097f0d271)

Yesterday it was like this (grabbed image from google)
![image](https://github.com/ManlyMarco/KK-HF_Patch/assets/112852330/b4ab87c8-1eb0-487f-944b-3d15365b939b)

not sure whether this is a problem with hf patch or just Koikatsu party itself

**Comment by BAP00tato** [comment]
I reinstalled HF patch and it went back to normal, jeez im having so many problems today

**Comment by ManlyMarco** [comment]
This happens when Steam updates your game, you have to reinstall HF Patch in that case or the game will likely be broken.
