### ISSUE TITLE
"this app cant run on your pc"

### ISSUE THREAD

**Issue by drakosoldier298** [ManlyMarco/KK-HF_Patch#72]
used webtorrent to download the patch 3.22 and it keeps giving this error when i try to run the exe

![image](https://github.com/ManlyMarco/KK-HF_Patch/assets/30358222/94334806-e320-4b39-9bd3-5f30e0024fe4)

**Comment by drakosoldier298** [comment]
rechecking files it seems the torrent didnt work properly. the exe and a few bins such as 12, 1, 5, 9, and 8 all have no data

**Comment by ManlyMarco** [comment]
Use latest version of qBittorrent to download the patch.
