### ISSUE TITLE
MOD Problem

### ISSUE THREAD

**Issue by an94444** [ManlyMarco/KK-HF_Patch#76]
HF3.23 can't raed scene data that mod name contain space save In old HF version .
As shown in the picture.

![image](https://github.com/ManlyMarco/KK-HF_Patch/assets/59949136/cada7065-e5f7-497c-84af-c1168d96381f)

Is there any good solution?

**Comment by ManlyMarco** [comment]
Update BepisPlugins.

**Comment by an94444** [comment]
thank you it's work
