### ISSUE TITLE
i can't change language this is what appears when u try to

### ISSUE THREAD

**Issue by ramfam1** [ManlyMarco/KK-HF_Patch#79]
Something went wrong when changing language: System.NullReferenceException: Object reference not set to an instance of an object
at
InitSetting.EnvironmentHelper.SetLanguage (System.String language) [0x002a9] in <da19a6ce8cb5445a870da9582 >:0

**Comment by ManlyMarco** [comment]
Can you post this issue in https://github.com/IllusionMods/IllusionLaunchers/issues ? Also include as much information about your setup as possible like folder paths or launcher version.
