### ISSUE TITLE
odd glitch with clothes in story mode

### ISSUE THREAD

**Issue by maxlefou** [ManlyMarco/KK-HF_Patch#8]
Sometimes, for reasons that seems to be random, some clothing parts of the girls gets removed. Talking to them might cause that, or just keeps them naked and all. It seems their clothes gets fixed when they change of map. That is, until it glitches again. It only affects the clothings and not the accessories.

After some tries, it looks like disabling "Persist cloth state in school" fixes the problem.

**Comment by ManlyMarco** [comment]
That's an issue with https://github.com/ManlyMarco/Koikatu-Overlay-Mods

Does this happen often? Do you know of a reliable way to reproduce this?

**Comment by maxlefou** [comment]
Pretty often, yes. The only way i know of doing this is starting a new game and get "Persist cloth state in school" enabled. Doing more tries for now.

**Comment by maxlefou** [comment]
Ok I'm not sure but it might not be a bug actually.

I spotted twice girls doing H together, and every time they kept themselves undressed around like i described before. And since it doesn't happen with the option "Persist cloth state in school" disabled, i'm starting to wonder if this option isn't actually doing this: keeping the clothing states of the girls after H and all. I was finding this odd but I guess some other people would like it. :p

Closing it since it's apparently not a glitch but a feature :p

**Comment by ManlyMarco** [comment]
This would be unintended if it happened, they should put their clothes back on after that. Can you turn off the "likes girls" trait for everyone and see if it still happens?

**Comment by maxlefou** [comment]
I don't think it's related to the Koikatu-Overlay-Mods since the "Persist cloth state in school" option is part of "Additionnal skin effects 1.6.1"
I also noticed the option below that one, "persist skin effects in school" has the same behavior. I had this enabled, then i Hed with a girl and she kept her virgin blood in when i Hed her again some minutes later while it usually gets washed off. So i'm pretty positive the bug i was mentionning was just actually normal behavior of the option in the mod "Additionnal skin effects 1.6.1"

Anyway, I tried with a new game with girls without the "likes girls" trait, and waited in the lockers, but nothing abnormal happened, even with the option enabled. Can't do more tests though, since i don't have debug mode in my game.

The thing you can do eventually maybe is to set these options disabled by default. :p

**Comment by ManlyMarco** [comment]
Ah, I meant Additionnal skin effects, yes. I'll just fix the clothes not getting reset after the lesbian H if that's the issue.
