### ISSUE TITLE
Accidentally Overwriting BepInEx folder

### ISSUE THREAD

**Issue by Kindomyyy** [ManlyMarco/KK-HF_Patch#81]
I didn't read what mods, plugins etc. including this and I installed XUnity AutoTranslator. I overwrited BepInEx folder and I think it changed something in Resource Redirector folder. I have slow internet, I can't reinstall it. pls help

**Comment by ManlyMarco** [comment]
Ask for help on the discord server or reinstall the patch and check removing all old plugins.
