### ISSUE TITLE
Strange HarvexARC and Vertex shader issue between HF and Madevil

### ISSUE THREAD

**Issue by alexchiu100014** [ManlyMarco/KK-HF_Patch#83]
So, my friends are using Madevil plugin pack and I'm the only one who use HF Patch.
And I found some problem when I tried to load their chara and scene card.
When I tried to load the card with HarvexARC or Vertex shader inside, it would appear：
![螢幕擷取畫面 2024-08-14 154854](https://github.com/user-attachments/assets/f2b1a277-dc6f-4308-9cc6-81a244df5423)
But I can load normally with Madevil plugin pack without any problem, so this is not a card corruption.
I found shader in Madevil looks like this：
![螢幕擷取畫面 2024-08-14 132024](https://github.com/user-attachments/assets/c1a7d53e-0f5c-4ce1-8453-43554e50587a)
And HF Patch looks like this：
![螢幕擷取畫面 2024-08-14 154935](https://github.com/user-attachments/assets/95698065-6c68-41b2-a275-bf5878ccfefd)
I need to use the "-" one instead of "/" one in HF Patch when I make my character, or it'll give me the same error.
![螢幕擷取畫面 2024-08-14 154854](https://github.com/user-attachments/assets/0aeb10a3-cd4d-4b7b-8b45-666aafef2912)
and using the "-" one would redirect me to the "/" one (Idk why my game function like this)
I think this is the problem why I can't read my friend's card properly.

Is this fixable by changing anything in my game folder, or this is a bug caused by HF or Madevil pack?

**Comment by alexchiu100014** [comment]
> Are you only changing the plugins folder without changing the mods folder? 
I only changed zipmod's manifest.xml but it didn't work.

> Try using older versions of MaterialEditor.
I would try old version of ME.

**Comment by ManlyMarco** [comment]
No, don't touch the zipmods. If the issue happens with everything other than plugins being identical then try finding the plugin that makes the difference.

**Comment by alexchiu100014** [comment]
Error is from Material Editor, but I don't know how old should I downgrade because I've downgraded to the same version what my friends use.
(Material Editor version is 3.5.0)
