### ISSUE TITLE
Koikatsu HF Patch v3.31.exe was quarantined by windows for being a severe trojan

### ISSUE THREAD

**Issue by lewieroo0** [ManlyMarco/KK-HF_Patch#84]
It says it detected a Trojan:Win32/Bearfoos.A!ml

Is this a false flag? I just want to make sure this is safe before installing anything.

**Comment by ManlyMarco** [comment]
If you downloaded it from links on my patreon page, most likely. Still, send the exe to virustotal and see if there are any solid detections before starting it.

**Comment by lewieroo0** [comment]
I downloaded it from the magnet on the patreon page. I did a scan on virustotal and only 1 out of 75 security vendors (MaxSecure) flagged it as unsafe

**Comment by rellikmil** [comment]
@ManlyMarco sorry for offtop, but I need ILLUSION FIELD HF Patch v1.1 (not 1.0), can you provide this to me?

**Comment by ManlyMarco** [comment]
I do not have the v1.1
