### ISSUE TITLE
Information about downloading the patch is incorrect.

### ISSUE THREAD

**Issue by dethzord** [ManlyMarco/KK-HF_Patch#86]
Link to Patreon does not allow downloading of patch without paying $5, contrary to information here.  Please update the page to reflect that, so people without patreon accounts don't waste their time creating an account they don't want for something they cannot download anyhow.

Also, the magnet link is very dead.  No, it isn't a settings issue.

**Comment by ManlyMarco** [comment]
It's not a settings issue (unless you went in and disabled DHT), it's a user issue. Read the download instructions, use the latest version of qBittorrent to open the magnet link. There are plenty of seeds up.
![image](https://github.com/user-attachments/assets/eb29a584-d893-4914-8e3d-a6ac8e28c0b4)
