### ISSUE TITLE
Possibility to uninstall specific mods?

### ISSUE THREAD

**Issue by SomeGuy87** [ManlyMarco/KK-HF_Patch#9]
Hi there,

I applied the HF patch and got the custom intro voices thing in, which I really want to get rid of again. Is there any possibility to just remove specific mods, as I also applied other mods that I don't want to remove with a re-installation of this package?

Thanks for any input :).

**Comment by ManlyMarco** [comment]
Currently you can use KK Manager to remove specific mods/plugins easily but it won't work with this specific mod.

There are plans for a completely new patcher that could do this, but it's still a while away.

**Comment by Pumabit** [comment]
When I try to install the current version of the HF Patch it says "This patch is inside of the game directory you are attempting to install to. You have to move the patch files outside of the game directory and try again". What does this mean?

**Comment by ManlyMarco** [comment]
It means that you are using a patch for a different game. Download the HF Patch made for the game you are trying to install it to.
